// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model_summary_activity.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SummaryActivity _$SummaryActivityFromJson(Map<String, dynamic> json) =>
    SummaryActivity(
      resourceState: (json['resource_state'] as num?)?.toInt(),
      athlete: json['athlete'] == null
          ? null
          : MetaAthlete.fromJson(json['athlete'] as Map<String, dynamic>),
      name: json['name'] as String?,
      distance: (json['distance'] as num?)?.toDouble(),
      movingTime: (json['moving_time'] as num?)?.toInt(),
      elapsedTime: (json['elapsed_time'] as num?)?.toInt(),
      totalElevationGain: (json['total_elevation_gain'] as num?)?.toDouble(),
      type: json['type'] as String?,
      workoutType: (json['workout_type'] as num?)?.toInt(),
      id: (json['id'] as num?)?.toInt(),
      externalId: json['external_id'] as String?,
      uploadId: (json['upload_id'] as num?)?.toInt(),
      startDate: json['start_date'] as String?,
      startDateLocal: json['start_date_local'] as String?,
      timezone: json['timezone'] as String?,
      utcOffset: (json['utc_offset'] as num?)?.toDouble(),
      startLatlng: _latLngFromJson(json['start_latlng']),
      endLatlng: _latLngFromJson(json['end_latlng']),
      locationCity: json['location_city'] as String?,
      locationState: json['location_state'] as String?,
      locationCountry: json['location_country'] as String?,
      achievementCount: (json['achievement_count'] as num?)?.toInt(),
      kudosCount: (json['kudos_count'] as num?)?.toInt(),
      commentCount: (json['comment_count'] as num?)?.toInt(),
      athleteCount: (json['athlete_count'] as num?)?.toInt(),
      photoCount: (json['photo_count'] as num?)?.toInt(),
      map: json['map'] == null
          ? null
          : PolyLineMap.fromJson(json['map'] as Map<String, dynamic>),
      trainer: json['trainer'] as bool?,
      commute: json['commute'] as bool?,
      manual: json['manual'] as bool?,
      private: json['private'] as bool?,
      flagged: json['flagged'] as bool?,
      gearId: json['gear_id'] as String?,
      fromAcceptedTag: json['from_accepted_tag'] as bool?,
      averageSpeed: (json['average_speed'] as num?)?.toDouble(),
      maxSpeed: (json['max_speed'] as num?)?.toDouble(),
      averageCadence: (json['average_cadence'] as num?)?.toDouble(),
      averageWatts: (json['average_watts'] as num?)?.toDouble(),
      weightedAverageWatts: (json['weighted_average_watts'] as num?)?.toInt(),
      kilojoules: (json['kilojoules'] as num?)?.toDouble(),
      deviceWatts: json['device_watts'] as bool?,
      hasHeartrate: json['has_heartrate'] as bool?,
      averageHeartrate: (json['average_heartrate'] as num?)?.toDouble(),
      maxHeartrate: (json['max_heartrate'] as num?)?.toDouble(),
      maxWatts: (json['max_watts'] as num?)?.toInt(),
      prCount: (json['pr_count'] as num?)?.toInt(),
      totalPhotoCount: (json['total_photo_count'] as num?)?.toInt(),
      hasKudoed: json['has_kudoed'] as bool?,
      sufferScore: (json['suffer_score'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$SummaryActivityToJson(SummaryActivity instance) =>
    <String, dynamic>{
      'resource_state': instance.resourceState,
      'athlete': ?instance.athlete?.toJson(),
      'name': instance.name,
      'distance': instance.distance,
      'moving_time': instance.movingTime,
      'elapsed_time': instance.elapsedTime,
      'total_elevation_gain': instance.totalElevationGain,
      'type': instance.type,
      'workout_type': instance.workoutType,
      'id': instance.id,
      'external_id': instance.externalId,
      'upload_id': instance.uploadId,
      'start_date': instance.startDate,
      'start_date_local': instance.startDateLocal,
      'timezone': instance.timezone,
      'utc_offset': instance.utcOffset,
      'start_latlng': instance.startLatlng,
      'end_latlng': instance.endLatlng,
      'location_city': instance.locationCity,
      'location_state': instance.locationState,
      'location_country': instance.locationCountry,
      'achievement_count': instance.achievementCount,
      'kudos_count': instance.kudosCount,
      'comment_count': instance.commentCount,
      'athlete_count': instance.athleteCount,
      'photo_count': instance.photoCount,
      'map': ?instance.map?.toJson(),
      'trainer': instance.trainer,
      'commute': instance.commute,
      'manual': instance.manual,
      'private': instance.private,
      'flagged': instance.flagged,
      'gear_id': instance.gearId,
      'from_accepted_tag': instance.fromAcceptedTag,
      'average_speed': instance.averageSpeed,
      'max_speed': instance.maxSpeed,
      'average_cadence': instance.averageCadence,
      'average_watts': instance.averageWatts,
      'weighted_average_watts': instance.weightedAverageWatts,
      'kilojoules': instance.kilojoules,
      'device_watts': instance.deviceWatts,
      'has_heartrate': instance.hasHeartrate,
      'average_heartrate': instance.averageHeartrate,
      'max_heartrate': instance.maxHeartrate,
      'max_watts': instance.maxWatts,
      'pr_count': instance.prCount,
      'total_photo_count': instance.totalPhotoCount,
      'has_kudoed': instance.hasKudoed,
      'suffer_score': instance.sufferScore,
    };
